mk_rxn_files('chem_Rx_Pax_Kathy');

scr='main_FVM';
fn=mk_fun2(scr);

call=[getFunctionHeader(fn) ';'];

eval(['try' newline...
    call newline...
    'catch err' newline...
    'disp(getReport(err));' newline...
    'end']);